const quizData = [
  {
    "id": "U01_001",
    "unit": "1. 文の成り立ち",
    "theme": "第1文型 (SV)",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "その店は6時に閉まる。",
    "words": ["6", "The", "at", "closes", "o'clock", "shop"],
    "correctOrder": ["The", "shop", "closes", "at", "6", "o'clock"],
    "explanation": "【第1文型】主語がThe shop、動詞がclosesのSV構造です。at 6 o'clockは時を表す修飾語（副詞句）であり、文の主要な骨格には含まれません。"
  },
  {
    "id": "U01_002",
    "unit": "1. 文の成り立ち",
    "theme": "第2文型 (SVC)",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "その本は面白かった。",
    "words": ["The", "book", "interesting", "was"],
    "correctOrder": ["The", "book", "was", "interesting"],
    "explanation": "【第2文型】主語がThe book、動詞がwas、補語がinterestingのSVC構造です。主語＝補語（The book = interesting）の関係が成り立ちます。"
  },
  {
    "id": "U01_003",
    "unit": "1. 文の成り立ち",
    "theme": "第3文型 (SVO)",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "彼は私の質問に答えた。",
    "words": ["He", "answered", "my", "question"],
    "correctOrder": ["He", "answered", "my", "question"],
    "explanation": "【第3文型】主語がHe、動詞がanswered、目的語がmy questionのSVO構造です。answerは他動詞なので、前置詞を伴わずに直接目的語をとる点に注意しましょう。"
  },
  {
    "id": "U01_004",
    "unit": "1. 文の成り立ち",
    "theme": "第4文型 (SVOO)",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "The photographer showed [   ] his photos.",
    "questionJa": "カメラマンは私たちに彼の写真を見せてくれた。",
    "choices": ["us", "to us", "we", "our"],
    "correctAnswer": "us",
    "explanation": "【第4文型】show O1 O2で「O1（人）にO2（物）を見せる」となります。to usと前置詞を入れる場合は、showed his photos to usのように語順が変わる点に注意しましょう。"
  },
  {
    "id": "U01_005",
    "unit": "1. 文の成り立ち",
    "theme": "第5文型 (SVOC)",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "私はこの本を読むのが難しいとわかった。",
    "words": ["I", "book", "difficult", "found", "read", "this", "to"],
    "correctOrder": ["I", "found", "this", "book", "difficult", "to", "read"],
    "explanation": "【第5文型】find O C で「OがCだとわかる」という構造を作ります。長文の中で見落としやすい「OとCの間にbe動詞を補って意味が通じる関係（this book = difficult）」に気づくことが読解の鍵です。"
  },
  {
    "id": "U01_006",
    "unit": "1. 文の成り立ち",
    "theme": "名詞句",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "私がロンドンを訪れるのはこれが初めてだ。",
    "words": ["London", "This", "first", "is", "my", "to", "visit"],
    "correctOrder": ["This", "is", "my", "first", "visit", "to", "London"],
    "explanation": "【名詞句】my first visit to London（私の初めてのロンドン訪問）が、2語以上で名詞の働きをする「名詞句」として文の補語（C）になっています。"
  },
  {
    "id": "U01_007",
    "unit": "1. 文の成り立ち",
    "theme": "形容詞句（分詞の後置修飾）",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "私は通りを歩いている女の子に話しかけた。",
    "words": ["I", "a", "girl", "on", "street", "talked", "the", "to", "walking"],
    "correctOrder": ["I", "talked", "to", "a", "girl", "walking", "on", "the", "street"],
    "explanation": "【形容詞句（現在分詞）】walking on the street という分詞のカタマリが、直前の名詞 girl を後ろから修飾しています。英語特有の「名詞＋後置修飾」の語順を前から処理する感覚を養いましょう。"
  },
  {
    "id": "U01_008",
    "unit": "1. 文の成り立ち",
    "theme": "副詞句（群前置詞）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "I had to cancel the trip [   ] ill health.",
    "questionJa": "私は体調不良のために旅行をキャンセルしなければならなかった。",
    "choices": ["because of", "because", "as", "since"],
    "correctAnswer": "because of",
    "explanation": "【副詞句】空所の後ろがSV（主語と動詞）を持つ「節」ではなく、ill healthという「名詞句」であることに注目します。名詞の前に置けるのは接続詞（because等）ではなく前置詞（because of）のみです。"
  },
  {
    "id": "U01_009",
    "unit": "1. 文の成り立ち",
    "theme": "名詞節（接続詞 if）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "I don't know [   ] Mary likes Chinese food.",
    "questionJa": "メアリーが中華料理を好きかどうか私は知らない。",
    "choices": ["if", "that", "what", "which"],
    "correctAnswer": "if",
    "explanation": "【名詞節】「〜かどうか」という不確実な内容を表す名詞節を作る接続詞 if を選びます。動詞 know の目的語となる大きなカタマリを作っているサインとして if に反応できるようにしましょう。"
  },
  {
    "id": "U01_010",
    "unit": "1. 文の成り立ち",
    "theme": "形容詞節（関係代名詞の省略）",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "その学生は図書館で借りた本を読んでいる。",
    "words": ["The", "a", "book", "borrowed", "from", "he", "is", "library", "reading", "student", "the"],
    "correctOrder": ["The", "student", "is", "reading", "a", "book", "he", "borrowed", "from", "the", "library"],
    "explanation": "【形容詞節】名詞(a book)の直後に主語と動詞(he borrowed...)が続く場合、関係代名詞が省略されています。長文でこの「名詞＋S＋V」のサインを見つけたら、前の名詞を修飾するカタマリだと判断しましょう。"
  },
  {
    "id": "U02_001",
    "unit": "2. 時制",
    "theme": "現在時制（一般的事実・状態）",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "数学と歴史は私のお気に入りの科目だ。",
    "words": ["Mathematics", "and", "are", "favorite", "history", "my", "subjects"],
    "correctOrder": ["Mathematics", "and", "history", "are", "my", "favorite", "subjects"],
    "explanation": "【現在時制】現在の状態や一般的な事実を述べる場合は現在時制を用います。Mathematics and history が複数扱いの主語となるため、動詞は are になります。"
  },
  {
    "id": "U02_002",
    "unit": "2. 時制",
    "theme": "現在時制（現在の習慣）",
    "difficulty": 1,
    "type": "choice",
    "questionEn": "I [   ] a cup of coffee every morning.",
    "questionJa": "私は毎朝コーヒーを飲む。",
    "choices": ["have", "am having", "had", "have had"],
    "correctAnswer": "have",
    "explanation": "【現在時制】every morning（毎朝）などの反復する現在の習慣を表す場合、現在進行形ではなく現在時制を使います。長文の中で時間の副詞句（every ~ や always など）を見たら、現在の習慣について述べていると判断しましょう。"
  },
  {
    "id": "U02_003",
    "unit": "2. 時制",
    "theme": "過去時制",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "その少年は昨日友達に会った。",
    "words": ["The", "boy", "friends", "his", "met", "yesterday"],
    "correctOrder": ["The", "boy", "met", "his", "friends", "yesterday"],
    "explanation": "【過去時制】yesterday（昨日）という過去の明確な時点を表す語句があるため、動詞は過去形（met）になります。長文では、過去を表す副詞句が時制を決定する重要なサインとなります。"
  },
  {
    "id": "U02_004",
    "unit": "2. 時制",
    "theme": "未来時制（時や条件を表す副詞節）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "I will call you when I [   ].",
    "questionJa": "到着したらあなたに電話します。",
    "choices": ["arrive", "will arrive", "arrived", "am arriving"],
    "correctAnswer": "arrive",
    "explanation": "【時・条件の副詞節】when や if が導く「時や条件を表す副詞節」の中では、未来の出来事であっても現在時制を用います。文意が未来であっても動詞の形が変わるため、長文読解時は when などの接続詞に注意しましょう。"
  },
  {
    "id": "U02_005",
    "unit": "2. 時制",
    "theme": "未来時制（予定・意図）",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "私たちはもうすぐ新しい車を買うつもりだ。",
    "words": ["We", "a", "are", "buy", "car", "going", "new", "soon", "to"],
    "correctOrder": ["We", "are", "going", "to", "buy", "a", "new", "car", "soon"],
    "explanation": "【未来時制】be going to do は、すでに心に決めている「予定・意図」を表します。soon（もうすぐ）のような未来を示す副詞とともに、筆者の今後の展開を予告する働きをします。"
  },
  {
    "id": "U02_006",
    "unit": "2. 時制",
    "theme": "過去進行形",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "通りを歩いていたとき、私はメアリーを見かけた。",
    "words": ["I", "I", "Mary", "When", "down", "saw", "street", "the", "walking", "was"],
    "correctOrder": ["When", "I", "was", "walking", "down", "the", "street", "I", "saw", "Mary"],
    "explanation": "【過去進行形】「〜していたとき」という過去のある時点における進行中の動作は、過去進行形（was/were + ~ing）で表します。when節（〜したとき）と組み合わさることで、出来事の背景状況を説明します。"
  },
  {
    "id": "U02_007",
    "unit": "2. 時制",
    "theme": "現在完了相（経験）",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "彼は私が今まで会った中で最も良い先生だ。",
    "words": ["He", "I", "best", "ever", "have", "is", "met", "teacher", "the"],
    "correctOrder": ["He", "is", "the", "best", "teacher", "I", "have", "ever", "met"],
    "explanation": "【現在完了（経験）】「これまでに〜したことがある」という経験を表す現在完了形（have + 過去分詞）です。the best（最上級）と I have ever met がセットになることで「これまでで最も〜だ」という強い主張を読み取ることができます。"
  },
  {
    "id": "U02_008",
    "unit": "2. 時制",
    "theme": "現在完了相（継続・期間）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "It has been a long time [   ] we last met.",
    "questionJa": "私たちが最後に会ってから長い時間が経った。",
    "choices": ["since", "for", "from", "when"],
    "correctAnswer": "since",
    "explanation": "【現在完了（継続）】「〜して以来」と過去の起点を示す場合は since を用います。It has been + 期間 + since + 過去形の文 は「〜してから…（期間）になる」という頻出構文なので、そのまま形を暗記しておきましょう。"
  },
  {
    "id": "U02_009",
    "unit": "2. 時制",
    "theme": "過去完了相（大過去）",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "私がパーティーに到着したとき、友人はすでに帰宅していた。",
    "words": ["I", "When", "already", "arrived", "at", "friend", "gone", "had", "home", "my", "party", "the"],
    "correctOrder": ["When", "I", "arrived", "at", "the", "party", "my", "friend", "had", "already", "gone", "home"],
    "explanation": "【過去完了】「到着した（過去）」よりも前に「帰宅していた」という「過去よりさらに前の出来事（大過去）」を表すため、had + 過去分詞 を使います。長文の中で複数の過去の出来事が登場した際、時間的な前後関係を整理する強力なサインとなります。"
  },
  {
    "id": "U02_010",
    "unit": "2. 時制",
    "theme": "現在完了進行形",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "あなたはここでどのくらいの間働いていますか？",
    "words": ["How", "been", "have", "here", "long", "working", "you"],
    "correctOrder": ["How", "long", "have", "you", "been", "working", "here"],
    "explanation": "【現在完了進行形】過去から現在まで動作が「ずっと継続している」ことを強調する場合、have been ~ing を用います。How long ~?（どのくらいの間）などの期間を問う表現と結びつきやすい点に注目しましょう。"
  },
  {
    "id": "U03_001",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "部分否定",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "このお金のすべてが私のものではない。",
    "words": ["Not", "all", "is", "mine", "money", "of", "this"],
    "correctOrder": ["Not", "all", "of", "this", "money", "is", "mine"],
    "explanation": "【部分否定】Not all 〜 で「すべてが〜というわけではない」という部分否定になります。「このお金のすべてが私のものではない（一部は違う）」という意味になります。"
  },
  {
    "id": "U03_002",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "準否定（数）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "He has [   ] friends here.",
    "questionJa": "彼にはここにはほとんど友達がいない。",
    "choices": ["few", "a few", "little", "a little"],
    "correctAnswer": "few",
    "explanation": "【準否定】few は可算名詞の複数形につき「ほとんど〜ない」という否定的な意味を表します。a few（少しいる）や、不可算名詞につく little との区別に注意しましょう。"
  },
  {
    "id": "U03_003",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "準否定（程度）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "My leg was hurting. I could [   ] walk.",
    "questionJa": "足が痛かった。私はほとんど歩くことができなかった。",
    "choices": ["hardly", "hard", "rarely", "seldom"],
    "correctAnswer": "hardly",
    "explanation": "【準否定】hardly は「程度」が「ほとんど〜ない」ことを表す副詞です。rarely や seldom は「頻度」が「めったに〜ない」ことを表すため、ここでは文脈上不適切です。"
  },
  {
    "id": "U03_004",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "二重否定",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "その少女は外出すると必ず傘をなくす。",
    "words": ["The", "girl", "goes", "her", "losing", "never", "out", "umbrella", "without"],
    "correctOrder": ["The", "girl", "never", "goes", "out", "without", "losing", "her", "umbrella"],
    "explanation": "【二重否定】never ... without ~ing で「...すれば必ず〜する（〜することなしに...しない）」という強い肯定の意味を表します。長文読解では、二つの否定語を打ち消し合って肯定で訳すと文脈が掴みやすくなります。"
  },
  {
    "id": "U03_005",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "受動態の基本",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "2000人がその会社に雇用されている。",
    "words": ["Two", "are", "by", "company", "employed", "people", "the", "thousand"],
    "correctOrder": ["Two", "thousand", "people", "are", "employed", "by", "the", "company"],
    "explanation": "【受動態】be動詞＋過去分詞（are employed）で「〜される（雇用されている）」という意味を表します。行為の主体は by ~ で示されることに注目しましょう。"
  },
  {
    "id": "U03_006",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "受動態（不規則動詞）",
    "difficulty": 1,
    "type": "choice",
    "questionEn": "A lot of money was [   ] in the robbery.",
    "questionJa": "その強盗事件で大金が盗まれた。",
    "choices": ["stolen", "stole", "steal", "stealing"],
    "correctAnswer": "stolen",
    "explanation": "【受動態】主語の A lot of money（大金）は「盗まれる」側なので、受動態（be動詞＋過去分詞）になります。steal（原形） - stole（過去形） - stolen（過去分詞）の不規則変化も確認しておきましょう。"
  },
  {
    "id": "U03_007",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "助動詞（否定の推量）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "It [   ] be true.",
    "questionJa": "それが本当であるはずがない。",
    "choices": ["can't", "mustn't", "shouldn't", "won't"],
    "correctAnswer": "can't",
    "explanation": "【助動詞】「〜のはずがない」という強い否定の推量は cannot (can't) を使います。must (〜に違いない) の反対の意味にあたります。mustn't は「〜してはいけない（禁止）」なので注意が必要です。"
  },
  {
    "id": "U03_008",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "助動詞＋完了形（推量）",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "彼らは外出したに違いない。",
    "words": ["They", "gone", "have", "must", "out"],
    "correctOrder": ["They", "must", "have", "gone", "out"],
    "explanation": "【助動詞＋完了形】must have + 過去分詞 で「（過去に）〜したに違いない」という過去の事象に対する強い推量を表します。長文の中で過去の出来事を振り返って考察する際に頻出します。"
  },
  {
    "id": "U03_009",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "助動詞（過去の習慣）",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "私は子供の頃、毎冬よくスキーに行ったものだ。",
    "words": ["When", "I", "I", "a", "child,", "every", "go", "skiing", "was", "winter", "would"],
    "correctOrder": ["When", "I", "was", "a", "child,", "I", "would", "go", "skiing", "every", "winter"],
    "explanation": "【助動詞】would (often) do で「（過去に）よく〜したものだ」という過去の習慣を表します。When I was a child のような過去の時を表す句や節とともに使われ、昔の回想を示すサインとなります。"
  },
  {
    "id": "U03_010",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "助動詞＋完了形（後悔・非難）",
    "difficulty": 3,
    "type": "choice",
    "questionEn": "You [   ] eaten so much.",
    "questionJa": "あなたはそんなにたくさん食べるべきではなかったのに。",
    "choices": ["shouldn't have", "must not have", "cannot have", "needn't have"],
    "correctAnswer": "shouldn't have",
    "explanation": "【助動詞＋完了形】shouldn't have + 過去分詞 で「（過去に）〜するべきではなかったのに（してしまった）」という後悔や非難を表します。筆者の主張や評価を読み取る上で非常に重要な表現です。"
  },
  {
    "id": "U04_001",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "不定詞の名詞的用法",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "外出するときはドアに鍵をかけるのを忘れないでください。",
    "words": ["Don't", "door", "forget", "go", "lock", "out", "the", "to", "when", "you"],
    "correctOrder": ["Don't", "forget", "to", "lock", "the", "door", "when", "you", "go", "out"],
    "explanation": "【名詞的用法】forget to do で「〜することを忘れる」という意味になります。to lock the door 全体が forget の目的語（名詞のカタマリ）として働いています。"
  },
  {
    "id": "U04_002",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "不定詞（形式主語）",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "運転免許を持っていることは役に立つ。",
    "words": ["It", "a", "driver's", "have", "is", "license", "to", "useful"],
    "correctOrder": ["It", "is", "useful", "to", "have", "a", "driver's", "license"],
    "explanation": "【名詞的用法】It is ~ to do の構文です。It は形式的な主語であり、本当の主語は to have a driver's license（運転免許を持っていること）になります。"
  },
  {
    "id": "U04_003",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "不定詞の形容詞的用法",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "They have sent the applicant a form to [   ] in.",
    "questionJa": "彼らは応募者に記入するための用紙を送った。",
    "choices": ["fill", "filling", "filled", "be filled"],
    "correctAnswer": "fill",
    "explanation": "【形容詞的用法】名詞 a form を後ろから修飾する to fill in（記入するための）という形容詞のカタマリを作ります。前置詞 in を忘れやすいので注意しましょう。"
  },
  {
    "id": "U04_004",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "不定詞の副詞的用法",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "私は英語を学ぶためにオーストラリアへ行く予定だ。",
    "words": ["Australia", "English", "I", "am", "going", "learn", "to", "to"],
    "correctOrder": ["I", "am", "going", "to", "Australia", "to", "learn", "English"],
    "explanation": "【副詞的用法】to learn English（英語を学ぶために）が目的を表す副詞のカタマリとして働いています。文の骨格（I am going to Australia）が完成した後に情報が追加される構造を意識しましょう。"
  },
  {
    "id": "U04_005",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "原形不定詞（知覚動詞）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "I didn't see her [   ] in.",
    "questionJa": "私は彼女が入ってくるのを見なかった。",
    "choices": ["come", "to come", "came", "comes"],
    "correctAnswer": "come",
    "explanation": "【原形不定詞】see O do（Oが〜するのを見る）という知覚動詞の構文では、to のない原形不定詞を使います。Oとdoの間に「彼女が入る」という主語・述語の関係が成り立ちます。"
  },
  {
    "id": "U04_006",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "原形不定詞（使役動詞）",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "私たちは子供たちに夜更かしをさせない。",
    "words": ["We", "children", "don't", "late", "let", "stay", "the", "up"],
    "correctOrder": ["We", "don't", "let", "the", "children", "stay", "up", "late"],
    "explanation": "【原形不定詞】let O do（Oに〜させる）という使役動詞の構文です。the children が stay up late するのを let（許可する）という論理構造を掴みましょう。"
  },
  {
    "id": "U04_007",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "現在分詞による後置修飾",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "あなたの友達と踊っている女の子は誰ですか？",
    "words": ["Who", "dancing", "friend", "girl", "is", "the", "with", "your"],
    "correctOrder": ["Who", "is", "the", "girl", "dancing", "with", "your", "friend"],
    "explanation": "【現在分詞】dancing with your friend という分詞のカタマリが、前の名詞 the girl を修飾しています。名詞の直後に ～ing が来た場合、修飾語の始まりを疑うのが読解のコツです。"
  },
  {
    "id": "U04_008",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "過去分詞による後置修飾",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "Do you know the number of people [   ] by the government?",
    "questionJa": "政府に雇用されている人々の数を知っていますか？",
    "choices": ["employed", "employing", "employ", "to employ"],
    "correctAnswer": "employed",
    "explanation": "【過去分詞】people employed by the government（政府に雇用されている人々）という受動の意味を持った過去分詞のカタマリです。名詞の後に過去分詞が置かれるパターンも長文頻出です。"
  },
  {
    "id": "U04_009",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "分詞構文",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "簡単な英語で書かれているので、この本は読みやすい。",
    "words": ["English,", "Written", "book", "easy", "in", "is", "read", "simple", "this", "to"],
    "correctOrder": ["Written", "in", "simple", "English,", "this", "book", "is", "easy", "to", "read"],
    "explanation": "【分詞構文】Written ~（書かれているので）という過去分詞から始まる副詞のカタマリが、主節の理由や条件などの状況を説明しています。主語（this book）との受動関係に注意しましょう。"
  },
  {
    "id": "U04_010",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "動名詞",
    "difficulty": 1,
    "type": "choice",
    "questionEn": "The doctor suggested [   ] a long holiday.",
    "questionJa": "医者は長期休暇を取ることを提案した。",
    "choices": ["taking", "to take", "take", "taken"],
    "correctAnswer": "taking",
    "explanation": "【動名詞】suggest（提案する）の目的語には、不定詞（to do）ではなく動名詞（~ing）を用います。「休暇を取ること」という名詞のカタマリを作っています。"
  },
  {
    "id": "U05_001",
    "unit": "5. 関係詞",
    "theme": "主格の関係代名詞",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "そのプロジェクトを率いている研究者は有名だ。",
    "words": ["famous", "is", "is", "leading", "project", "researcher", "The", "the", "who"],
    "correctOrder": ["The", "researcher", "who", "is", "leading", "the", "project", "is", "famous"],
    "explanation": "【主格の関係代名詞】who is leading the project という関係代名詞の節が、直前の名詞（先行詞）The researcher を修飾しています。主語が長くなるため、2つ目の is が文全体の述語動詞であることを見抜くのが読解のポイントです。"
  },
  {
    "id": "U05_002",
    "unit": "5. 関係詞",
    "theme": "目的格の関係代名詞（省略）",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "私たちが先週雇った従業員はとても優秀だ。",
    "words": ["capable", "employee", "hired", "is", "last", "The", "very", "we", "week"],
    "correctOrder": ["The", "employee", "we", "hired", "last", "week", "is", "very", "capable"],
    "explanation": "【目的格の関係代名詞】名詞（The employee）の直後にS+V（we hired）が続く場合、目的格の関係代名詞（whom/that）が省略されています。「名詞＋S＋V」の語順は、長文読解において後置修飾の強力なサインとなります。"
  },
  {
    "id": "U05_003",
    "unit": "5. 関係詞",
    "theme": "所有格の関係代名詞",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "The company [   ] products are famous is expanding.",
    "questionJa": "その製品が有名な企業は事業を拡大している。",
    "choices": ["whose", "which", "of which", "that"],
    "correctAnswer": "whose",
    "explanation": "【所有格の関係代名詞】先行詞（The company）と関係詞節内の名詞（products）の間に「企業の製品（the company's products）」という所有の関係が成り立つため、whose が正解です。"
  },
  {
    "id": "U05_004",
    "unit": "5. 関係詞",
    "theme": "関係代名詞 what",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "重要なのは、我々が次に何をすべきかだ。",
    "words": ["do", "important", "is", "is", "next", "should", "we", "What", "what"],
    "correctOrder": ["What", "is", "important", "is", "what", "we", "should", "do", "next"],
    "explanation": "【関係代名詞 what】what は「〜するもの・こと」という意味の名詞節を作ります。文頭の What is important（重要なこと）が主語となり、後半の what we should do next（我々が次にすべきこと）が補語となる構造です。"
  },
  {
    "id": "U05_005",
    "unit": "5. 関係詞",
    "theme": "前置詞＋関係代名詞",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "これが彼が担当している資料だ。",
    "words": ["document", "for", "he", "is", "is", "responsible", "the", "This", "which"],
    "correctOrder": ["This", "is", "the", "document", "for", "which", "he", "is", "responsible"],
    "explanation": "【前置詞＋関係代名詞】be responsible for ~（〜を担当している）の for が関係代名詞 which の前に移動した形です。長文で「前置詞＋which/whom」を見たら、その後ろには完全な文（S+V...）が続くと予測しましょう。"
  },
  {
    "id": "U05_006",
    "unit": "5. 関係詞",
    "theme": "関係代名詞の非制限用法",
    "difficulty": 3,
    "type": "choice",
    "questionEn": "I tried to open the door, [   ] I found impossible.",
    "questionJa": "私はドアを開けようとしたが、それは不可能だとわかった。",
    "choices": ["which", "that", "it", "what"],
    "correctAnswer": "which",
    "explanation": "【非制限用法】カンマ（,）に続く関係代名詞 which は、直前の名詞だけでなく、前の文全体（ドアを開けようとしたこと）を先行詞として受けることができます。that は非制限用法（カンマの後）では使えないため注意が必要です。"
  },
  {
    "id": "U05_007",
    "unit": "5. 関係詞",
    "theme": "関係副詞 where",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "これがその事故が起こった交差点だ。",
    "words": ["accident", "happened", "intersection", "is", "the", "the", "This", "where"],
    "correctOrder": ["This", "is", "the", "intersection", "where", "the", "accident", "happened"],
    "explanation": "【関係副詞】先行詞が場所（intersection：交差点）であり、後ろの文が the accident happened（事故が起こった）という完全な構造（第1文型）になっているため、関係代名詞ではなく関係副詞 where を用いて修飾します。"
  },
  {
    "id": "U05_008",
    "unit": "5. 関係詞",
    "theme": "関係副詞 why",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "Tell me the reason [   ] you were late for the meeting.",
    "questionJa": "会議に遅れた理由を教えてください。",
    "choices": ["why", "which", "what", "how"],
    "correctAnswer": "why",
    "explanation": "【関係副詞】先行詞が the reason（理由）のときは、関係副詞 why を使います。後ろの you were late for the meeting が完全な文であることからも、関係副詞が入ることが論理的に判断できます。"
  },
  {
    "id": "U05_009",
    "unit": "5. 関係詞",
    "theme": "関係副詞 how",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "このようにして彼はその問題を解決した。",
    "words": ["he", "how", "is", "problem", "solved", "the", "This"],
    "correctOrder": ["This", "is", "how", "he", "solved", "the", "problem"],
    "explanation": "【関係副詞】This is how S+V ~ は「このようにしてSは〜する」というプロセスや手段を表す重要構文です。how 自体が「〜する方法」という名詞節を作るため、先行詞 the way を一緒に置かないのがルールです。"
  },
  {
    "id": "U05_010",
    "unit": "5. 関係詞",
    "theme": "複合関係代名詞",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "誰でも最初に来た人がそのチケットをもらえる。",
    "words": ["can", "comes", "first", "get", "the", "ticket", "Whoever"],
    "correctOrder": ["Whoever", "comes", "first", "can", "get", "the", "ticket"],
    "explanation": "【複合関係代名詞】whoever（〜する人は誰でも）が名詞節を作り、文全体の主語になっています。anyone who comes first と書き換えることもでき、条件や譲歩のニュアンスを含む読解のキーフレーズとなります。"
  },
  {
    "id": "U06_001",
    "unit": "6. 比較",
    "theme": "原級を用いた比較",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "彼は私と同じくらい一生懸命に働いた。",
    "words": ["as", "hard", "He", "as", "I", "worked", "did"],
    "correctOrder": ["He", "worked", "as", "hard", "as", "I", "did"],
    "explanation": "【原級比較】as + 形容詞/副詞 + as で「〜と同じくらい…」という比較を表します。比較対象が文（I did）の場合は as I did となる点に注意しましょう。"
  },
  {
    "id": "U06_002",
    "unit": "6. 比較",
    "theme": "比較級＋than",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "この車はあの車より速い。",
    "words": ["car", "faster", "is", "than", "that", "This", "one"],
    "correctOrder": ["This", "car", "is", "faster", "than", "that", "one"],
    "explanation": "【比較級】形容詞・副詞の比較級（faster）＋ than で「〜より…だ」という比較を表します。one は直前の car を繰り返すのを避けるための代名詞です。"
  },
  {
    "id": "U06_003",
    "unit": "6. 比較",
    "theme": "最上級の表現",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "This is the [   ] book I have ever read.",
    "questionJa": "これは私が今まで読んだ中で最も興味深い本だ。",
    "choices": ["most interesting", "more interesting", "interesting", "as interesting"],
    "correctAnswer": "most interesting",
    "explanation": "【最上級】「〜の中で最も…」という最上級には the + 最上級 の形を使います。ever read（今まで〜した中で）と結びついて強い印象を表す長文の頻出パターンです。"
  },
  {
    "id": "U06_004",
    "unit": "6. 比較",
    "theme": "倍数表現",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "この部屋はあの部屋の3倍の大きさだ。",
    "words": ["as", "as", "is", "large", "room", "that", "three", "This", "times", "room"],
    "correctOrder": ["This", "room", "is", "three", "times", "as", "large", "as", "that", "room"],
    "explanation": "【倍数表現】A times as + 原級 + as B で「AはBの何倍…だ」となります。この構文は論理的な比較や数値の変動を示す文章で非常に重要な役割を果たします。"
  },
  {
    "id": "U06_005",
    "unit": "6. 比較",
    "theme": "比較級を使った構文（The 比較級...）",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "経験を積めば積むほど、ますます賢くなる。",
    "words": ["experience", "more", "The", "the", "we", "we", "wiser", "get", "gain"],
    "correctOrder": ["The", "more", "experience", "we", "gain", "the", "wiser", "we", "get"],
    "explanation": "【比較構文】The + 比較級 S V, the + 比較級 S V で「〜すればするほど、ますます…だ」となります。因果関係や論理展開を説明する文脈で筆者が主張を強調するために使われます。"
  },
  {
    "id": "U06_006",
    "unit": "6. 比較",
    "theme": "比較対象の代用（that of）",
    "difficulty": 3,
    "type": "choice",
    "questionEn": "The population of Tokyo is larger than [   ] of Osaka.",
    "questionJa": "東京の人口は大阪のそれ（人口）より多い。",
    "choices": ["that", "those", "it", "this"],
    "correctAnswer": "that",
    "explanation": "【比較対象】比較対象を一致させる必要があります。population（単数名詞）を指す代名詞には that を使います。those は複数名詞を指す場合に使うので間違いに注意しましょう。"
  },
  {
    "id": "U06_007",
    "unit": "6. 比較",
    "theme": "no more than",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "彼はわずか10ドルしか持っていない。",
    "words": ["than", "has", "more", "He", "no", "ten", "dollars"],
    "correctOrder": ["He", "has", "no", "more", "than", "ten", "dollars"],
    "explanation": "【否定比較】no more than は「（数値を強調して）たった〜（わずか〜）」という意味になります。直訳すると「10ドルより多くはない」となります。"
  },
  {
    "id": "U06_008",
    "unit": "6. 比較",
    "theme": "比較級の重要表現（no longer）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "He [   ] lives here.",
    "questionJa": "彼はもはやここには住んでいない。",
    "choices": ["no longer", "any longer", "not long", "no more"],
    "correctAnswer": "no longer",
    "explanation": "【比較表現】no longer は「もはや〜ない」という状態の変化を表す重要表現です。文の動詞の前に置くのが基本ルールです。"
  },
  {
    "id": "U06_009",
    "unit": "6. 比較",
    "theme": "最上級の強調",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "彼はクラスで断然背が高い。",
    "words": ["by", "class", "far", "He", "is", "tallest", "the", "in", "the"],
    "correctOrder": ["He", "is", "by", "far", "the", "tallest", "in", "the", "class"],
    "explanation": "【最上級強調】by far は最上級（the tallest）を強調し「断然〜、ずば抜けて〜」という意味になります。比較級にも使えますが、最上級とも相性が良い表現です。"
  },
  {
    "id": "U06_010",
    "unit": "6. 比較",
    "theme": "比較級の慣用表現",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "She is [   ] than pretty.",
    "questionJa": "彼女は可愛いというよりむしろ賢い。",
    "choices": ["wiser", "more wise", "as wise", "the wise"],
    "correctAnswer": "wiser",
    "explanation": "【比較慣用】A rather than B（BというよりむしろA）と同じ意味を、more + 原形形容詞 + than で表します。賢い（wise）という単語は一音節なので wiser と比較級にします。"
  },
  {
    "id": "U07_001",
    "unit": "7. 仮定法",
    "theme": "仮定法過去",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "私があなたなら、その提案を受け入れるだろう。",
    "words": ["I", "I", "If", "accept", "proposal", "the", "were", "would", "you"],
    "correctOrder": ["If", "I", "were", "you", "I", "would", "accept", "the", "proposal"],
    "explanation": "【仮定法過去】現在の事実とは異なる「もし〜なら」を過去形を用いて表します。長文読解では、If 節の過去形（were）と主節の助動詞の過去形（would）のセットを見たら「筆者の反実仮想（事実に反する仮定）」のサインと捉えましょう。"
  },
  {
    "id": "U07_002",
    "unit": "7. 仮定法",
    "theme": "仮定法過去完了",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "もし真実を知っていたら、私はあなたに話していただろう。",
    "words": ["I", "I", "If", "had", "have", "known", "the", "told", "truth", "would", "you"],
    "correctOrder": ["If", "I", "had", "known", "the", "truth", "I", "would", "have", "told", "you"],
    "explanation": "【仮定法過去完了】過去の事実とは異なる仮定を表します。had + 過去分詞 と would have + 過去分詞 の組み合わせがサインです。過去の出来事に対する筆者の後悔や「別の可能性（もし〜だったら）」を示す重要な構文です。"
  },
  {
    "id": "U07_003",
    "unit": "7. 仮定法",
    "theme": "if の省略による倒置",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "もし私があなたの立場なら、同じことをするだろう。",
    "words": ["I", "I", "Were", "do", "in", "position", "same", "the", "would", "your"],
    "correctOrder": ["Were", "I", "in", "your", "position", "I", "would", "do", "the", "same"],
    "explanation": "【倒置構文】If I were in your position の If が省略されると、Were I という疑問文のような語順（倒置）になります。文頭に Were, Had, Should が来て疑問文ではない場合、仮定法の倒置を疑うのが長文読解の鉄則です。"
  },
  {
    "id": "U07_004",
    "unit": "7. 仮定法",
    "theme": "混合型仮定法",
    "difficulty": 3,
    "type": "choice",
    "questionEn": "If I had taken the medicine then, I [   ] fine now.",
    "questionJa": "もしあの時薬を飲んでいたら、今は元気になっているだろう。",
    "choices": ["would be", "will be", "would have been", "am"],
    "correctAnswer": "would be",
    "explanation": "【混合型仮定法】前半が「過去の仮定（had taken）」、後半が「現在の結果（would be）」となる複合パターンです。then（あの時）や now（今）などの「時を表す副詞」が、時制のズレを見抜く決定的なマーカーになります。"
  },
  {
    "id": "U07_005",
    "unit": "7. 仮定法",
    "theme": "I wish 構文",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "私はもっと上手に英語を話せたらよいのにと思う。",
    "words": ["English", "I", "I", "better", "could", "speak", "wish"],
    "correctOrder": ["I", "wish", "I", "could", "speak", "English", "better"],
    "explanation": "【I wish 構文】「〜であればいいのに」という現在の叶わぬ願望を表します。wish の後ろの節の動詞が過去形（could speak）になることに注意してください。長文では筆者の強い願望や現状への不満を読み取るポイントになります。"
  },
  {
    "id": "U07_006",
    "unit": "7. 仮定法",
    "theme": "as if 構文",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "彼はまるで幽霊でも見たかのように話す。",
    "words": ["He", "a", "as", "ghost", "had", "he", "if", "seen", "talks"],
    "correctOrder": ["He", "talks", "as", "if", "he", "had", "seen", "a", "ghost"],
    "explanation": "【as if 構文】「まるで〜であるかのように」という意味の重要構文です。as if の後ろが仮定法過去完了（had seen）になることで、「実際には幽霊を見ていない」という比喩表現であることが論理的に判断できます。"
  },
  {
    "id": "U07_007",
    "unit": "7. 仮定法",
    "theme": "without を用いた仮定法",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "あなたの財政的な支援がなかったら、そのプロジェクトは失敗していただろう。",
    "words": ["Without", "failed", "financial", "have", "project", "support", "the", "would", "your"],
    "correctOrder": ["Without", "your", "financial", "support", "the", "project", "would", "have", "failed"],
    "explanation": "【without 構文】Without 〜 で「〜がなかったら」という条件節の代わりになります。主節に would have failed が続くことで、これが単なる前置詞ではなく仮定法であると気づくことができます。"
  },
  {
    "id": "U07_008",
    "unit": "7. 仮定法",
    "theme": "It is time 構文",
    "difficulty": 3,
    "type": "choice",
    "questionEn": "It is high time you [   ] an independent life.",
    "questionJa": "あなたはもう自立した生活を送ってもよい頃だ。",
    "choices": ["started", "start", "will start", "have started"],
    "correctAnswer": "started",
    "explanation": "【It is time 構文】「もう（とっくに）〜してもよい時間だ」という意味です。time の後ろの節の動詞が仮定法過去形（started）になるのが最大の特徴です。筆者の「早くそうすべきだ」という強い主張や焦りを示すサインとなります。"
  },
  {
    "id": "U07_009",
    "unit": "7. 仮定法",
    "theme": "万が一の should",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "万一、彼が来たら、私に電話するように伝えてください。",
    "words": ["If", "call", "come", "he", "him", "me", "should", "tell", "to"],
    "correctOrder": ["If", "he", "should", "come", "tell", "him", "to", "call", "me"],
    "explanation": "【should を用いた仮定法】If 節の中に should を用いると、「万が一〜したら」という未来の実現可能性が極めて低い仮定を表します。主節にはこの文のように命令文（tell him...）が続くことが多い点も特徴です。"
  },
  {
    "id": "U07_010",
    "unit": "7. 仮定法",
    "theme": "副詞 otherwise",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "I started early; [   ], I would have missed the train.",
    "questionJa": "私は早く出発した。そうでなければ、列車に乗り遅れていただろう。",
    "choices": ["otherwise", "therefore", "however", "moreover"],
    "correctAnswer": "otherwise",
    "explanation": "【副詞による仮定法】otherwise は「そうでなければ」と、直前の事実と反対の仮定を表す副詞です。長文の論理展開において、もし違う選択をしていたらどうなっていたかを示す非常に重要なディスコースマーカー（論理の標識）です。"
  },
    {
    "id": "U08_001",
    "unit": "8. 話法・代名詞・接続詞",
    "theme": "話法（平叙文の伝達）",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "彼は財布をなくしたと私に言った。",
    "words": ["He", "had", "he", "his", "lost", "me", "that", "told", "wallet"],
    "correctOrder": ["He", "told", "me", "that", "he", "had", "lost", "his", "wallet"],
    "explanation": "【話法】「Sに〜だと言う」は tell O that S V で表します。主節の動詞（told）が過去形のため、that節の中の時制も過去完了（had lost）に一致しています。"
  },
  {
    "id": "U08_002",
    "unit": "8. 話法・代名詞・接続詞",
    "theme": "話法（疑問文の伝達）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "She asked me [   ] I lived.",
    "questionJa": "彼女は私がどこに住んでいるのか私に尋ねた。",
    "choices": ["where", "what", "which", "how"],
    "correctAnswer": "where",
    "explanation": "【話法】疑問詞で始まる疑問文を間接話法にする場合、ask O + 疑問詞 + S + V の語順（間接疑問文）になります。「どこに」を表す where が入ります。"
  },
  {
    "id": "U08_003",
    "unit": "8. 話法・代名詞・接続詞",
    "theme": "話法（命令文の伝達）",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "医者は彼にタバコをやめるように忠告した。",
    "words": ["The", "advised", "doctor", "him", "smoking", "stop", "to"],
    "correctOrder": ["The", "doctor", "advised", "him", "to", "stop", "smoking"],
    "explanation": "【話法】advise O to do で「Oに〜するように忠告する」という意味になります。命令や依頼を間接話法で伝える際の頻出パターンです。tell O to do や ask O to do と同じ構造です。"
  },
  {
    "id": "U08_004",
    "unit": "8. 話法・代名詞・接続詞",
    "theme": "時制の一致",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "私は彼がその試験に合格するだろうと思った。",
    "words": ["I", "exam", "he", "pass", "that", "the", "thought", "would"],
    "correctOrder": ["I", "thought", "that", "he", "would", "pass", "the", "exam"],
    "explanation": "【時制の一致】主節の動詞（thought）が過去形なので、従属節（that節）の助動詞も will から would に過去形へと変化します。"
  },
  {
    "id": "U08_005",
    "unit": "8. 話法・代名詞・接続詞",
    "theme": "不定代名詞（another / the other）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "I don't like this design. Please show me [   ].",
    "questionJa": "私はこのデザインが好きではありません。別のものを見せてください。",
    "choices": ["another", "other", "the other", "others"],
    "correctAnswer": "another",
    "explanation": "【代名詞】「（不特定の）もう1つの別のもの」を指す場合は another を使います。the other は「（残りすべてのうちの）もう1つ」を指すため、文脈上ここでは不適切です。"
  },
  {
    "id": "U08_006",
    "unit": "8. 話法・代名詞・接続詞",
    "theme": "代名詞（Those who ~）",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "そのプロジェクトに興味がある人は会議に出席すべきだ。",
    "words": ["Those", "are", "attend", "in", "interested", "meeting", "project", "should", "the", "the", "who"],
    "correctOrder": ["Those", "who", "are", "interested", "in", "the", "project", "should", "attend", "the", "meeting"],
    "explanation": "【代名詞】Those who ~ で「〜する人々」という重要な働きをします。長文で筆者が一般論や特定の集団について述べる際によく使われる表現です。"
  },
  {
    "id": "U08_007",
    "unit": "8. 話法・代名詞・接続詞",
    "theme": "相関接続詞（not only A but also B）",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "生徒たちだけでなく先生も驚いた。",
    "words": ["Not", "also", "but", "only", "students", "surprised", "teacher", "the", "the", "was"],
    "correctOrder": ["Not", "only", "the", "students", "but", "also", "the", "teacher", "was", "surprised"],
    "explanation": "【相関接続詞】not only A but also B（AだけでなくBも）が主語になる場合、動詞はB（ここでは the teacher）の数に一致するため、were ではなく was になる点に注意しましょう。"
  },
  {
    "id": "U08_008",
    "unit": "8. 話法・代名詞・接続詞",
    "theme": "時を表す接続詞（as soon as）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "[   ] he arrived at the station, it began to rain.",
    "questionJa": "彼が駅に着くとすぐに雨が降り始めた。",
    "choices": ["As soon as", "As far as", "As long as", "As well as"],
    "correctAnswer": "As soon as",
    "explanation": "【接続詞】As soon as S V で「SがVするとすぐに」という時の副詞節を作ります。as far as（〜する限りでは：範囲）や as long as（〜する間は：時間・条件）との意味の違いに注意しましょう。"
  },
  {
    "id": "U08_009",
    "unit": "8. 話法・代名詞・接続詞",
    "theme": "前置詞（despite）",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "悪天候にもかかわらず、彼らはピクニックに出かけた。",
    "words": ["Despite", "a", "bad", "on", "picnic", "the", "they", "weather", "went"],
    "correctOrder": ["Despite", "the", "bad", "weather", "they", "went", "on", "a", "picnic"],
    "explanation": "【前置詞】Despite は「〜にもかかわらず」という意味の前置詞で、後ろには名詞（句）が続きます。接続詞の Although（後ろにS+Vが続く）との使い分けが文法問題や読解の鍵になります。"
  },
  {
    "id": "U08_010",
    "unit": "8. 話法・代名詞・接続詞",
    "theme": "条件の接続詞（unless）",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "急がない限り、あなたはバスに乗り遅れるだろう。",
    "words": ["Unless", "bus", "hurry", "miss", "the", "will", "you", "you"],
    "correctOrder": ["Unless", "you", "hurry", "you", "will", "miss", "the", "bus"],
    "explanation": "【接続詞】Unless は「〜しない限り」という意味の接続詞で、If ~ not とほぼ同じ働きをします。Unless 自体に否定の意味が含まれているため、後ろの文（you hurry）は肯定形になります。"
  },
  {
    "id": "U09_001",
    "unit": "9. 重要構文・語彙の応用 (1)",
    "theme": "第5文型 (SVOC) ＋重要語彙",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "私はその従業員が有能だとわかった。",
    "words": ["capable", "employee", "found", "I", "the"],
    "correctOrder": ["I", "found", "the", "employee", "capable"],
    "explanation": "【第5文型】find O C（OがCだとわかる）の構造に、重要語彙 employee（従業員）と capable（有能な）を組み込んだ形です。長文では単語が難しくなっても文の骨格を瞬時に見抜くことが重要です。"
  },
  {
    "id": "U09_002",
    "unit": "9. 重要構文・語彙の応用 (1)",
    "theme": "形式目的語 (take it for granted)",
    "difficulty": 3,
    "type": "choice",
    "questionEn": "The politician takes [   ] for granted that he should apologize.",
    "questionJa": "その政治家は自分が謝罪すべきだと当然のように思っている。",
    "choices": ["it", "this", "that", "them"],
    "correctAnswer": "it",
    "explanation": "【形式目的語】take it for granted that 〜 で「〜ということを当然だと思う」という重要イディオムです。it は that 以下を指す形式目的語であり、長文の論理展開を掴むための重要なサインとなります。politician（政治家）、apologize（謝罪する）も頻出語です。"
  },
  {
    "id": "U09_003",
    "unit": "9. 重要構文・語彙の応用 (1)",
    "theme": "否定を表す重要構文 (far from)",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "その解決策は妥当には程遠かった。",
    "words": ["far", "from", "reasonable", "solution", "The", "was"],
    "correctOrder": ["The", "solution", "was", "far", "from", "reasonable"],
    "explanation": "【強い否定表現】far from 〜 は「〜には程遠い、決して〜ない」という強い否定を表す重要構文です。not を使わずに否定の意味を持つため、読解時に筆者の批判的なスタンスを読み取る強力なマーカーになります。solution（解決策）、reasonable（妥当な）とセットで覚えましょう。"
  },
  {
    "id": "U09_004",
    "unit": "9. 重要構文・語彙の応用 (1)",
    "theme": "否定を表す重要構文 (the last person)",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "彼は最も不正をしそうにない人だ。",
    "words": ["cheat", "He", "is", "last", "person", "the", "to"],
    "correctOrder": ["He", "is", "the", "last", "person", "to", "cheat"],
    "explanation": "【強い否定表現】the last person to do は「最も〜しそうにない人（決して〜しない人）」という意味の重要構文です。肯定文の形をしていますが、意味は強い否定になる点に注意が必要です。cheat（不正をする・ごまかす）という単語のニュアンスも押さえておきましょう。"
  },
  {
    "id": "U09_005",
    "unit": "9. 重要構文・語彙の応用 (1)",
    "theme": "倒置構文 (No sooner ~ than)",
    "difficulty": 3,
    "type": "choice",
    "questionEn": "No sooner had he arrived at the conference [   ] it began.",
    "questionJa": "彼が会議に到着するとすぐにそれは始まった。",
    "choices": ["than", "when", "that", "before"],
    "correctAnswer": "than",
    "explanation": "【倒置構文】No sooner had S V than ... で「SがVするとすぐに…」という構文です。否定語（No sooner）が文頭に出ることで had S V という疑問文の語順（倒置）が起きています。比較級 sooner が使われているため、呼応する接続詞は than になります。conference（会議）などの単語とともに出題されやすい形です。"
  },
  {
    "id": "U09_006",
    "unit": "9. 重要構文・語彙の応用 (1)",
    "theme": "前置詞 ＋ 重要語彙",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "疲労にもかかわらず、そのアスリートは奮闘した。",
    "words": ["athlete", "Despite", "fatigue,", "his", "struggled", "the"],
    "correctOrder": ["Despite", "his", "fatigue,", "the", "athlete", "struggled"],
    "explanation": "【前置詞】Despite は「〜にもかかわらず」を表す前置詞で、後ろに名詞句（his fatigue）を取ります。fatigue（疲労）、athlete（運動選手）、struggle（奮闘する）といった重要語彙と論理展開のサインを同時に処理しましょう。"
  },
  {
    "id": "U09_007",
    "unit": "9. 重要構文・語彙の応用 (1)",
    "theme": "関係代名詞 ＋ 重要語彙",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "Candidates [   ] oppose the policy should resign.",
    "questionJa": "その政策に反対する候補者は辞任すべきだ。",
    "choices": ["who", "which", "whom", "what"],
    "correctAnswer": "who",
    "explanation": "【主格の関係代名詞】Candidates（候補者たち）を先行詞とし、後ろの動詞 oppose（〜に反対する）の主語となる主格の関係代名詞 who を選びます。policy（政策）や resign（辞任する）など、政治・ビジネス系の長文で頻出する語彙の組み合わせです。"
  },
  {
    "id": "U09_008",
    "unit": "9. 重要構文・語彙の応用 (1)",
    "theme": "無生物主語 ＋ 重要語彙",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "その病気は患者を絶望させた。",
    "words": ["desperate", "disease", "made", "patient", "The", "the"],
    "correctOrder": ["The", "disease", "made", "the", "patient", "desperate"],
    "explanation": "【無生物主語】The disease（病気）という無生物が主語になり、make O C で「OをCの状態にする」という因果関係（原因と結果）を表しています。desperate（絶望した・必死の）や patient（患者）の語彙とともに、長文の論理（なぜそうなったか）を把握する力が問われます。"
  },
  {
    "id": "U09_009",
    "unit": "9. 重要構文・語彙の応用 (1)",
    "theme": "最上級の強調 ＋ 重要語彙",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "この解決策は断然最も信頼できる。",
    "words": ["by", "far", "is", "most", "reliable", "solution", "the", "This"],
    "correctOrder": ["This", "solution", "is", "by", "far", "the", "most", "reliable"],
    "explanation": "【最上級の強調】by far は the most reliable（最も信頼できる）という最上級を強調し、「断然、ずば抜けて」という意味を加えます。solution（解決策）を評価する筆者の強い主張を読み取るためのサインです。"
  },
  {
    "id": "U09_010",
    "unit": "9. 重要構文・語彙の応用 (1)",
    "theme": "動名詞を目的語にとる動詞",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "The committee suggested [   ] the election.",
    "questionJa": "委員会は選挙を延期することを提案した。",
    "choices": ["postponing", "to postpone", "postpone", "postponed"],
    "correctAnswer": "postponing",
    "explanation": "【動名詞】suggest（〜を提案する）の目的語には不定詞ではなく動名詞（~ing）をとります。committee（委員会）、postpone（〜を延期する）、election（選挙）など、長文でよく目にする語彙と文法規則をリンクさせておきましょう。"
  },
  {
    "id": "U10_001",
    "unit": "10. 重要構文・語彙の応用 (2)",
    "theme": "不定代名詞を用いた構文 (It is no use ~ing)",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "その決定について不満を言っても無駄だ。",
    "words": ["about", "complaining", "decision", "is", "It", "no", "the", "use"],
    "correctOrder": ["It", "is", "no", "use", "complaining", "about", "the", "decision"],
    "explanation": "【重要構文】It is no use ~ing で「〜しても無駄だ」という構文です。it は形式主語で、~ing の部分が真主語になります。complain（不満を言う）や decision（決定）といった語彙とセットで、筆者の「意味がない」という主張を読み取りましょう。"
  },
  {
    "id": "U10_002",
    "unit": "10. 重要構文・語彙の応用 (2)",
    "theme": "不定詞を用いた構文 (too ~ to ...)",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "The problem was [   ] complicated for me to solve.",
    "questionJa": "その問題は私が解決するには複雑すぎた。",
    "choices": ["too", "so", "very", "much"],
    "correctAnswer": "too",
    "explanation": "【不定詞の重要構文】too ~ to do で「〜すぎて…できない」という否定の意味を含みます。complicated（複雑な）や solve（解決する）といった語彙の組み合わせで、文面に not がなくても否定として訳出する精読力が問われます。"
  },
  {
    "id": "U10_003",
    "unit": "10. 重要構文・語彙の応用 (2)",
    "theme": "結果を表す構文 (so ~ that ...)",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "その講義はとても退屈だったので、私は眠ってしまった。",
    "words": ["asleep", "boring", "fell", "I", "lecture", "so", "that", "The", "was"],
    "correctOrder": ["The", "lecture", "was", "so", "boring", "that", "I", "fell", "asleep"],
    "explanation": "【結果の構文】so ~ that S V で「とても〜なので（その結果）SはVだ」という因果関係を表します。lecture（講義）が boring（退屈な）であったことと、眠ってしまった結果が that によって論理的に結ばれています。"
  },
  {
    "id": "U10_004",
    "unit": "10. 重要構文・語彙の応用 (2)",
    "theme": "相関接続詞 (not only A but also B)",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "彼は英語だけでなくフランス語も流暢に話す。",
    "words": ["also", "but", "English", "fluently", "French", "He", "not", "only", "speaks"],
    "correctOrder": ["He", "speaks", "not", "only", "English", "but", "also", "French", "fluently"],
    "explanation": "【相関構文】not only A but also B で「AだけでなくBも」という意味になります。筆者はAよりもBの方を強調したい（新情報として伝えたい）という論理展開のサインになるため、長文で非常に重要です。"
  },
  {
    "id": "U10_005",
    "unit": "10. 重要構文・語彙の応用 (2)",
    "theme": "強調構文 (It is ~ that ...)",
    "difficulty": 3,
    "type": "choice",
    "questionEn": "It was the manager [   ] canceled the meeting.",
    "questionJa": "会議をキャンセルしたのはマネージャーだった。",
    "choices": ["that", "what", "which", "whom"],
    "correctAnswer": "that",
    "explanation": "【強調構文】It is (was) 〜 that ... で「…なのは〜だ」と、〜の部分を強調します。ここでは the manager（マネージャー）を強調しています。cancel（キャンセルする）という事実に対して、誰が主導したのかを正確に読み取るサインになります。"
  },
  {
    "id": "U10_006",
    "unit": "10. 重要構文・語彙の応用 (2)",
    "theme": "否定語の倒置 (Little did I ...)",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "私は彼女に再び会うとは全く予期していなかった。",
    "words": ["again", "did", "expect", "her", "I", "Little", "see", "to"],
    "correctOrder": ["Little", "did", "I", "expect", "to", "see", "her", "again"],
    "explanation": "【倒置構文】Little や Never などの否定語が文頭に出ると、後ろが「助動詞＋S＋V」の疑問文の語順（倒置）になります。expect（予期する）と結びつき「全く予期していなかった」という筆者の強い感情や驚きを表します。"
  },
  {
    "id": "U10_007",
    "unit": "10. 重要構文・語彙の応用 (2)",
    "theme": "強い否定を表す重要表現 (by no means)",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "その結果は決して満足のいくものではなかった。",
    "words": ["by", "means", "no", "result", "satisfactory", "The", "was"],
    "correctOrder": ["The", "result", "was", "by", "no", "means", "satisfactory"],
    "explanation": "【強い否定】by no means は「決して〜ない」という強い否定を表す熟語です。result（結果）や satisfactory（満足のいく）などの単語と結びつき、筆者の評価や結論を決定づける重要な表現です。"
  },
  {
    "id": "U10_008",
    "unit": "10. 重要構文・語彙の応用 (2)",
    "theme": "否定を含まない否定表現 (free from)",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "This document is free [   ] errors.",
    "questionJa": "この書類には誤りがない。",
    "choices": ["from", "of", "with", "without"],
    "correctAnswer": "from",
    "explanation": "【否定の重要表現】be free from 〜 で「（苦痛や誤りなど）好ましくないものがない」という意味を表します。not を使わずに否定の意味を持つため、document（書類）などの情報を正確に読み取る際に重要です。"
  },
  {
    "id": "U10_009",
    "unit": "10. 重要構文・語彙の応用 (2)",
    "theme": "比較の重要構文 (as ~ as possible)",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "私はできるだけ早くそのタスクを完了させる必要がある。",
    "words": ["as", "as", "complete", "I", "need", "possible", "soon", "task", "the", "to"],
    "correctOrder": ["I", "need", "to", "complete", "the", "task", "as", "soon", "as", "possible"],
    "explanation": "【比較構文】as ~ as possible で「できるだけ〜」という意味になります。complete（完了させる）、task（タスク・仕事）などの語彙と組み合わされ、ビジネスや日常の文脈で頻出します。"
  },
  {
    "id": "U10_010",
    "unit": "10. 重要構文・語彙の応用 (2)",
    "theme": "接続詞の後の主語・be動詞の省略",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "日本に滞在している間、彼は多くの神社を訪れた。",
    "words": ["he", "in", "Japan,", "many", "shrines", "staying", "visited", "While"],
    "correctOrder": ["While", "staying", "in", "Japan,", "he", "visited", "many", "shrines"],
    "explanation": "【省略構文】While (he was) staying in Japan のように、時や条件を表す接続詞の直後では「主語＋be動詞」が省略されることがよくあります。分詞構文のように見えますが、接続詞の意味を明確に残した形です。"
  },
  {
    "id": "U11_001",
    "unit": "11. 重要熟語と論理マーカー (1)",
    "theme": "熟語 (turn down)",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "彼女の昇給の要求は却下された。",
    "words": ["a", "down", "for", "Her", "raise", "request", "turned", "was"],
    "correctOrder": ["Her", "request", "for", "a", "raise", "was", "turned", "down"],
    "explanation": "【熟語】turn down は「〜を拒絶する、却下する」という意味の重要熟語です。受動態（was turned down）の形でよく使われ、筆者の否定的な展開を読み取るサインになります。"
  },
  {
    "id": "U11_002",
    "unit": "11. 重要熟語と論理マーカー (1)",
    "theme": "熟語 (be opposed to)",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "Most of us are opposed [   ] the death penalty.",
    "questionJa": "私たちのほとんどは死刑に反対している。",
    "choices": ["to", "against", "for", "with"],
    "correctAnswer": "to",
    "explanation": "【熟語】be opposed to 〜 で「〜に反対している」状態を表します。この to は不定詞ではなく前置詞なので、後ろには名詞（the death penalty）や動名詞が続く点に注意しましょう。"
  },
  {
    "id": "U11_003",
    "unit": "11. 重要熟語と論理マーカー (1)",
    "theme": "論理マーカー (have ~ in common with)",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "日本文化は中国文化と共通点が多い。",
    "words": ["a", "Chinese", "common", "culture", "culture", "has", "in", "Japanese", "lot", "with"],
    "correctOrder": ["Japanese", "culture", "has", "a", "lot", "in", "common", "with", "Chinese", "culture"],
    "explanation": "【熟語】have A in common with B で「Bと共通してAを持つ」という意味になります。長文の中で比較や対比の論理展開を示す強力なサイン（ディスコースマーカー）です。"
  },
  {
    "id": "U11_004",
    "unit": "11. 重要熟語と論理マーカー (1)",
    "theme": "論理マーカー (in terms of)",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "彼はすべてをお金の観点から考える傾向がある。",
    "words": ["everything", "He", "in", "money", "of", "of", "tends", "terms", "think", "to"],
    "correctOrder": ["He", "tends", "to", "think", "of", "everything", "in", "terms", "of", "money"],
    "explanation": "【熟語】in terms of 〜 は「〜の観点から、〜の基準で」という意味です。筆者がどのような評価基準で物事を論じているかを示す重要な表現です。tend to（〜する傾向がある）も頻出です。"
  },
  {
    "id": "U11_005",
    "unit": "11. 重要熟語と論理マーカー (1)",
    "theme": "論理マーカー (as well as)",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "The city is famous for its history [   ] its food.",
    "questionJa": "その都市は食べ物だけでなく歴史でも有名だ。",
    "choices": ["as well as", "as far as", "as long as", "as soon as"],
    "correctAnswer": "as well as",
    "explanation": "【論理マーカー】A as well as B で「BだけでなくAも」という情報の追加を表します。not only B but also A と同じ論理展開（Bは当然として、さらにAも）を作ります。"
  },
  {
    "id": "U11_006",
    "unit": "11. 重要熟語と論理マーカー (1)",
    "theme": "論理マーカー (On the other hand)",
    "difficulty": 1,
    "type": "choice",
    "questionEn": "[   ], some people agree with the plan.",
    "questionJa": "一方で、その計画に賛成する人もいる。",
    "choices": ["On the other hand", "In other words", "As a result", "For instance"],
    "correctAnswer": "On the other hand",
    "explanation": "【論理マーカー】On the other hand は「一方で」と対比や逆接を表す重要なディスコースマーカーです。前後の文で異なる意見や側面が対比されていることに注目しましょう。"
  },
  {
    "id": "U11_007",
    "unit": "11. 重要熟語と論理マーカー (1)",
    "theme": "因果関係 (result in)",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "大雨が洪水を引き起こした（洪水という結果になった）。",
    "words": ["a", "flood", "heavy", "in", "rain", "resulted", "The"],
    "correctOrder": ["The", "heavy", "rain", "resulted", "in", "a", "flood"],
    "explanation": "【熟語】result in 〜 で「〜という結果になる（＝〜を引き起こす）」という意味になります。主語が原因、in の後ろが結果となる因果関係（原因→結果）を表す重要表現です。"
  },
  {
    "id": "U11_008",
    "unit": "11. 重要熟語と論理マーカー (1)",
    "theme": "因果関係 (depend on)",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "プロジェクトの成功はあなたの努力次第だ。",
    "words": ["depends", "effort", "of", "on", "project", "success", "The", "the", "your"],
    "correctOrder": ["The", "success", "of", "the", "project", "depends", "on", "your", "effort"],
    "explanation": "【熟語】depend on 〜 は「〜に依存する、〜次第である」という意味です。長文では、何が何に影響を与えているかの論理構造（条件や因果関係）を掴む鍵になります。"
  },
  {
    "id": "U11_009",
    "unit": "11. 重要熟語と論理マーカー (1)",
    "theme": "熟語 (look forward to ~ing)",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "I am looking forward to [   ] from you.",
    "questionJa": "あなたからの連絡を楽しみにしています。",
    "choices": ["hearing", "hear", "be heard", "have heard"],
    "correctAnswer": "hearing",
    "explanation": "【熟語】look forward to 〜ing で「〜するのを楽しみに待つ」という意味です。この to は不定詞ではなく前置詞なので、後ろには動詞の原形ではなく動名詞（~ing）が来ます。"
  },
  {
    "id": "U11_010",
    "unit": "11. 重要熟語と論理マーカー (1)",
    "theme": "熟語 (take place)",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "会議は次の月曜日に行われる。",
    "words": ["meeting", "Monday", "next", "place", "take", "The", "will"],
    "correctOrder": ["The", "meeting", "will", "take", "place", "next", "Monday"],
    "explanation": "【熟語】take place は「（予定されていたことが）行われる、開催される」という意味です。意味の中に「行われる」という受身のニュアンスが含まれているため、受動態にはならない点に注意しましょう。"
  },
  {
    "id": "U12_001",
    "unit": "12. 重要熟語と論理マーカー (2)",
    "theme": "因果関係 (bring about)",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "その新しい技術は私たちの生活に大きな変化をもたらした。",
    "words": ["The", "a", "about", "brought", "change", "great", "in", "lives", "new", "our", "technology"],
    "correctOrder": ["The", "new", "technology", "brought", "about", "a", "great", "change", "in", "our", "lives"],
    "explanation": "【熟語】bring about（〜を引き起こす、もたらす）は長文の因果関係（原因→結果）を示す重要な熟語です。technology（技術）などの無生物が主語になり、事象の変化を述べる展開に慣れましょう。"
  },
  {
    "id": "U12_002",
    "unit": "12. 重要熟語と論理マーカー (2)",
    "theme": "熟語 (figure out)",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "私はその機械の操作方法を理解することができなかった。",
    "words": ["I", "couldn't", "figure", "how", "machine", "operate", "out", "the", "to"],
    "correctOrder": ["I", "couldn't", "figure", "out", "how", "to", "operate", "the", "machine"],
    "explanation": "【熟語】figure out（〜を理解する、解決する）は頻出熟語です。how to operate（どのように操作するか）という疑問詞＋不定詞の名詞のカタマリを目的語にとっています。"
  },
  {
    "id": "U12_003",
    "unit": "12. 重要熟語と論理マーカー (2)",
    "theme": "熟語 (take advantage of)",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "You should take [   ] of this opportunity.",
    "questionJa": "あなたはこの機会を利用するべきだ。",
    "choices": ["advantage", "care", "part", "pride"],
    "correctAnswer": "advantage",
    "explanation": "【熟語】take advantage of 〜 で「（機会や状況などを）利用する」という意味の重要熟語です。opportunity（機会）とセットで出題されることが多く、筆者の主張やアドバイスの文脈でよく見られます。"
  },
  {
    "id": "U12_004",
    "unit": "12. 重要熟語と論理マーカー (2)",
    "theme": "熟語 (pay attention to)",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "学生たちは先生の言うことに注意を払わなければならない。",
    "words": ["Students", "attention", "must", "pay", "says", "teacher", "the", "to", "what"],
    "correctOrder": ["Students", "must", "pay", "attention", "to", "what", "the", "teacher", "says"],
    "explanation": "【熟語】pay attention to 〜 で「〜に注意を払う」という意味です。to は不定詞ではなく前置詞なので、後ろには名詞または名詞節（what the teacher says：先生が言うこと）が続きます。"
  },
  {
    "id": "U12_005",
    "unit": "12. 重要熟語と論理マーカー (2)",
    "theme": "無生物主語構文 (prevent A from ~ing)",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "悪天候のため、私たちは出発できなかった。",
    "words": ["The", "bad", "from", "leaving", "prevented", "us", "weather"],
    "correctOrder": ["The", "bad", "weather", "prevented", "us", "from", "leaving"],
    "explanation": "【無生物主語】prevent A from ~ing は「Aが〜するのを防ぐ・妨げる」という構文の代表格です。直訳の「悪天候が私たちを妨げた」から「悪天候のために出発できなかった」と因果関係で訳せるようにしましょう。"
  },
  {
    "id": "U12_006",
    "unit": "12. 重要熟語と論理マーカー (2)",
    "theme": "熟語 (be used to ~ing)",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "I am not used to [   ] in public.",
    "questionJa": "私は人前で話すことには慣れていない。",
    "choices": ["speaking", "speak", "spoken", "be spoken"],
    "correctAnswer": "speaking",
    "explanation": "【熟語】be used to ~ing で「〜することに慣れている」という状態を表します。to は不定詞の記号ではなく前置詞なので、後ろには動詞の原形ではなく動名詞（~ing）が来る点に注意が必要です。"
  },
  {
    "id": "U12_007",
    "unit": "12. 重要熟語と論理マーカー (2)",
    "theme": "動詞の語法 (remind A of B)",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "この歌は私に故郷を思い出させる。",
    "words": ["This", "hometown", "me", "my", "of", "reminds", "song"],
    "correctOrder": ["This", "song", "reminds", "me", "of", "my", "hometown"],
    "explanation": "【語法】remind A of B で「AにBを思い出させる」という語法です。of は「分離」や「関連」を表す前置詞であり、この形を見たら「Aの頭の中にBの情報を呼び起こす」というイメージを持ちましょう。"
  },
  {
    "id": "U12_008",
    "unit": "12. 重要熟語と論理マーカー (2)",
    "theme": "因果関係 (due to)",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "He was late [   ] a traffic jam.",
    "questionJa": "交通渋滞のために彼は遅刻した。",
    "choices": ["due to", "because", "since", "as"],
    "correctAnswer": "due to",
    "explanation": "【群前置詞】due to 〜 は「〜のために、〜が原因で」という意味の前置詞のカタマリです。because of と同様に、後ろには文（S+V）ではなく名詞句が続き、因果関係（結果 due to 原因）を示す論理マーカーとなります。"
  },
  {
    "id": "U12_009",
    "unit": "12. 重要熟語と論理マーカー (2)",
    "theme": "熟語 (play a role in)",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "教育は社会において重要な役割を果たす。",
    "words": ["Education", "an", "important", "in", "plays", "role", "society"],
    "correctOrder": ["Education", "plays", "an", "important", "role", "in", "society"],
    "explanation": "【熟語】play a role in 〜 で「〜において役割を果たす」という意味になります。important（重要な）や key（鍵となる）などの形容詞を伴って、主題の重要性を述べるトピックセンテンスによく使われます。"
  },
  {
    "id": "U12_010",
    "unit": "12. 重要熟語と論理マーカー (2)",
    "theme": "熟語 (be likely to do)",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "今夜は雨が降りそうだ。",
    "words": ["It", "is", "likely", "rain", "to", "tonight"],
    "correctOrder": ["It", "is", "likely", "to", "rain", "tonight"],
    "explanation": "【熟語】be likely to do は「〜しそうである、〜する可能性が高い」という傾向や未来の予測を表す重要表現です。長文では、研究結果からの推測や一般的な傾向を述べる際によく登場します。"
  }
];
