const quizData = [
  {
    "id": "U01_001",
    "unit": "1. 文の成り立ち",
    "theme": "第1文型 (SV)",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "その店は6時に閉まる。",
    "words": ["6", "The", "at", "closes", "o'clock", "shop"],
    "correctOrder": ["The", "shop", "closes", "at", "6", "o'clock"],
    "explanation": "【第1文型】主語がThe shop、動詞がclosesのSV構造です。at 6 o'clockは時を表す修飾語（副詞句）であり、文の主要な骨格には含まれません。"
  },
  {
    "id": "U01_002",
    "unit": "1. 文の成り立ち",
    "theme": "第2文型 (SVC)",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "その本は面白かった。",
    "words": ["The", "book", "interesting", "was"],
    "correctOrder": ["The", "book", "was", "interesting"],
    "explanation": "【第2文型】主語がThe book、動詞がwas、補語がinterestingのSVC構造です。主語＝補語（The book = interesting）の関係が成り立ちます。"
  },
  {
    "id": "U01_003",
    "unit": "1. 文の成り立ち",
    "theme": "第3文型 (SVO)",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "彼は私の質問に答えた。",
    "words": ["He", "answered", "my", "question"],
    "correctOrder": ["He", "answered", "my", "question"],
    "explanation": "【第3文型】主語がHe、動詞がanswered、目的語がmy questionのSVO構造です。answerは他動詞なので、前置詞を伴わずに直接目的語をとる点に注意しましょう。"
  },
  {
    "id": "U01_004",
    "unit": "1. 文の成り立ち",
    "theme": "第4文型 (SVOO)",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "The photographer showed [   ] his photos.",
    "questionJa": "カメラマンは私たちに彼の写真を見せてくれた。",
    "choices": ["us", "to us", "we", "our"],
    "correctAnswer": "us",
    "explanation": "【第4文型】show O1 O2で「O1（人）にO2（物）を見せる」となります。to usと前置詞を入れる場合は、showed his photos to usのように語順が変わる点に注意しましょう。"
  },
  {
    "id": "U01_005",
    "unit": "1. 文の成り立ち",
    "theme": "第5文型 (SVOC)",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "私はこの本を読むのが難しいとわかった。",
    "words": ["I", "book", "difficult", "found", "read", "this", "to"],
    "correctOrder": ["I", "found", "this", "book", "difficult", "to", "read"],
    "explanation": "【第5文型】find O C で「OがCだとわかる」という構造を作ります。長文の中で見落としやすい「OとCの間にbe動詞を補って意味が通じる関係（this book = difficult）」に気づくことが読解の鍵です。"
  },
  {
    "id": "U01_006",
    "unit": "1. 文の成り立ち",
    "theme": "名詞句",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "私がロンドンを訪れるのはこれが初めてだ。",
    "words": ["London", "This", "first", "is", "my", "to", "visit"],
    "correctOrder": ["This", "is", "my", "first", "visit", "to", "London"],
    "explanation": "【名詞句】my first visit to London（私の初めてのロンドン訪問）が、2語以上で名詞の働きをする「名詞句」として文の補語（C）になっています。"
  },
  {
    "id": "U01_007",
    "unit": "1. 文の成り立ち",
    "theme": "形容詞句（分詞の後置修飾）",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "私は通りを歩いている女の子に話しかけた。",
    "words": ["I", "a", "girl", "on", "street", "talked", "the", "to", "walking"],
    "correctOrder": ["I", "talked", "to", "a", "girl", "walking", "on", "the", "street"],
    "explanation": "【形容詞句（現在分詞）】walking on the street という分詞のカタマリが、直前の名詞 girl を後ろから修飾しています。英語特有の「名詞＋後置修飾」の語順を前から処理する感覚を養いましょう。"
  },
  {
    "id": "U01_008",
    "unit": "1. 文の成り立ち",
    "theme": "副詞句（群前置詞）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "I had to cancel the trip [   ] ill health.",
    "questionJa": "私は体調不良のために旅行をキャンセルしなければならなかった。",
    "choices": ["because of", "because", "as", "since"],
    "correctAnswer": "because of",
    "explanation": "【副詞句】空所の後ろがSV（主語と動詞）を持つ「節」ではなく、ill healthという「名詞句」であることに注目します。名詞の前に置けるのは接続詞（because等）ではなく前置詞（because of）のみです。"
  },
  {
    "id": "U01_009",
    "unit": "1. 文の成り立ち",
    "theme": "名詞節（接続詞 if）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "I don't know [   ] Mary likes Chinese food.",
    "questionJa": "メアリーが中華料理を好きかどうか私は知らない。",
    "choices": ["if", "that", "what", "which"],
    "correctAnswer": "if",
    "explanation": "【名詞節】「〜かどうか」という不確実な内容を表す名詞節を作る接続詞 if を選びます。動詞 know の目的語となる大きなカタマリを作っているサインとして if に反応できるようにしましょう。"
  },
  {
    "id": "U01_010",
    "unit": "1. 文の成り立ち",
    "theme": "形容詞節（関係代名詞の省略）",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "その学生は図書館で借りた本を読んでいる。",
    "words": ["The", "a", "book", "borrowed", "from", "he", "is", "library", "reading", "student", "the"],
    "correctOrder": ["The", "student", "is", "reading", "a", "book", "he", "borrowed", "from", "the", "library"],
    "explanation": "【形容詞節】名詞(a book)の直後に主語と動詞(he borrowed...)が続く場合、関係代名詞が省略されています。長文でこの「名詞＋S＋V」のサインを見つけたら、前の名詞を修飾するカタマリだと判断しましょう。"
  },
  {
    "id": "U02_001",
    "unit": "2. 時制",
    "theme": "現在時制（一般的事実・状態）",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "数学と歴史は私のお気に入りの科目だ。",
    "words": ["Mathematics", "and", "are", "favorite", "history", "my", "subjects"],
    "correctOrder": ["Mathematics", "and", "history", "are", "my", "favorite", "subjects"],
    "explanation": "【現在時制】現在の状態や一般的な事実を述べる場合は現在時制を用います。Mathematics and history が複数扱いの主語となるため、動詞は are になります。"
  },
  {
    "id": "U02_002",
    "unit": "2. 時制",
    "theme": "現在時制（現在の習慣）",
    "difficulty": 1,
    "type": "choice",
    "questionEn": "I [   ] a cup of coffee every morning.",
    "questionJa": "私は毎朝コーヒーを飲む。",
    "choices": ["have", "am having", "had", "have had"],
    "correctAnswer": "have",
    "explanation": "【現在時制】every morning（毎朝）などの反復する現在の習慣を表す場合、現在進行形ではなく現在時制を使います。長文の中で時間の副詞句（every ~ や always など）を見たら、現在の習慣について述べていると判断しましょう。"
  },
  {
    "id": "U02_003",
    "unit": "2. 時制",
    "theme": "過去時制",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "その少年は昨日友達に会った。",
    "words": ["The", "boy", "friends", "his", "met", "yesterday"],
    "correctOrder": ["The", "boy", "met", "his", "friends", "yesterday"],
    "explanation": "【過去時制】yesterday（昨日）という過去の明確な時点を表す語句があるため、動詞は過去形（met）になります。長文では、過去を表す副詞句が時制を決定する重要なサインとなります。"
  },
  {
    "id": "U02_004",
    "unit": "2. 時制",
    "theme": "未来時制（時や条件を表す副詞節）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "I will call you when I [   ].",
    "questionJa": "到着したらあなたに電話します。",
    "choices": ["arrive", "will arrive", "arrived", "am arriving"],
    "correctAnswer": "arrive",
    "explanation": "【時・条件の副詞節】when や if が導く「時や条件を表す副詞節」の中では、未来の出来事であっても現在時制を用います。文意が未来であっても動詞の形が変わるため、長文読解時は when などの接続詞に注意しましょう。"
  },
  {
    "id": "U02_005",
    "unit": "2. 時制",
    "theme": "未来時制（予定・意図）",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "私たちはもうすぐ新しい車を買うつもりだ。",
    "words": ["We", "a", "are", "buy", "car", "going", "new", "soon", "to"],
    "correctOrder": ["We", "are", "going", "to", "buy", "a", "new", "car", "soon"],
    "explanation": "【未来時制】be going to do は、すでに心に決めている「予定・意図」を表します。soon（もうすぐ）のような未来を示す副詞とともに、筆者の今後の展開を予告する働きをします。"
  },
  {
    "id": "U02_006",
    "unit": "2. 時制",
    "theme": "過去進行形",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "通りを歩いていたとき、私はメアリーを見かけた。",
    "words": ["I", "I", "Mary", "When", "down", "saw", "street", "the", "walking", "was"],
    "correctOrder": ["When", "I", "was", "walking", "down", "the", "street", "I", "saw", "Mary"],
    "explanation": "【過去進行形】「〜していたとき」という過去のある時点における進行中の動作は、過去進行形（was/were + ~ing）で表します。when節（〜したとき）と組み合わさることで、出来事の背景状況を説明します。"
  },
  {
    "id": "U02_007",
    "unit": "2. 時制",
    "theme": "現在完了相（経験）",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "彼は私が今まで会った中で最も良い先生だ。",
    "words": ["He", "I", "best", "ever", "have", "is", "met", "teacher", "the"],
    "correctOrder": ["He", "is", "the", "best", "teacher", "I", "have", "ever", "met"],
    "explanation": "【現在完了（経験）】「これまでに〜したことがある」という経験を表す現在完了形（have + 過去分詞）です。the best（最上級）と I have ever met がセットになることで「これまでで最も〜だ」という強い主張を読み取ることができます。"
  },
  {
    "id": "U02_008",
    "unit": "2. 時制",
    "theme": "現在完了相（継続・期間）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "It has been a long time [   ] we last met.",
    "questionJa": "私たちが最後に会ってから長い時間が経った。",
    "choices": ["since", "for", "from", "when"],
    "correctAnswer": "since",
    "explanation": "【現在完了（継続）】「〜して以来」と過去の起点を示す場合は since を用います。It has been + 期間 + since + 過去形の文 は「〜してから…（期間）になる」という頻出構文なので、そのまま形を暗記しておきましょう。"
  },
  {
    "id": "U02_009",
    "unit": "2. 時制",
    "theme": "過去完了相（大過去）",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "私がパーティーに到着したとき、友人はすでに帰宅していた。",
    "words": ["I", "When", "already", "arrived", "at", "friend", "gone", "had", "home", "my", "party", "the"],
    "correctOrder": ["When", "I", "arrived", "at", "the", "party", "my", "friend", "had", "already", "gone", "home"],
    "explanation": "【過去完了】「到着した（過去）」よりも前に「帰宅していた」という「過去よりさらに前の出来事（大過去）」を表すため、had + 過去分詞 を使います。長文の中で複数の過去の出来事が登場した際、時間的な前後関係を整理する強力なサインとなります。"
  },
  {
    "id": "U02_010",
    "unit": "2. 時制",
    "theme": "現在完了進行形",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "あなたはここでどのくらいの間働いていますか？",
    "words": ["How", "been", "have", "here", "long", "working", "you"],
    "correctOrder": ["How", "long", "have", "you", "been", "working", "here"],
    "explanation": "【現在完了進行形】過去から現在まで動作が「ずっと継続している」ことを強調する場合、have been ~ing を用います。How long ~?（どのくらいの間）などの期間を問う表現と結びつきやすい点に注目しましょう。"
  },
  {
    "id": "U03_001",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "部分否定",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "このお金のすべてが私のものではない。",
    "words": ["Not", "all", "is", "mine", "money", "of", "this"],
    "correctOrder": ["Not", "all", "of", "this", "money", "is", "mine"],
    "explanation": "【部分否定】Not all 〜 で「すべてが〜というわけではない」という部分否定になります。「このお金のすべてが私のものではない（一部は違う）」という意味になります。"
  },
  {
    "id": "U03_002",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "準否定（数）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "He has [   ] friends here.",
    "questionJa": "彼にはここにはほとんど友達がいない。",
    "choices": ["few", "a few", "little", "a little"],
    "correctAnswer": "few",
    "explanation": "【準否定】few は可算名詞の複数形につき「ほとんど〜ない」という否定的な意味を表します。a few（少しいる）や、不可算名詞につく little との区別に注意しましょう。"
  },
  {
    "id": "U03_003",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "準否定（程度）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "My leg was hurting. I could [   ] walk.",
    "questionJa": "足が痛かった。私はほとんど歩くことができなかった。",
    "choices": ["hardly", "hard", "rarely", "seldom"],
    "correctAnswer": "hardly",
    "explanation": "【準否定】hardly は「程度」が「ほとんど〜ない」ことを表す副詞です。rarely や seldom は「頻度」が「めったに〜ない」ことを表すため、ここでは文脈上不適切です。"
  },
  {
    "id": "U03_004",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "二重否定",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "その少女は外出すると必ず傘をなくす。",
    "words": ["The", "girl", "goes", "her", "losing", "never", "out", "umbrella", "without"],
    "correctOrder": ["The", "girl", "never", "goes", "out", "without", "losing", "her", "umbrella"],
    "explanation": "【二重否定】never ... without ~ing で「...すれば必ず〜する（〜することなしに...しない）」という強い肯定の意味を表します。長文読解では、二つの否定語を打ち消し合って肯定で訳すと文脈が掴みやすくなります。"
  },
  {
    "id": "U03_005",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "受動態の基本",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "2000人がその会社に雇用されている。",
    "words": ["Two", "are", "by", "company", "employed", "people", "the", "thousand"],
    "correctOrder": ["Two", "thousand", "people", "are", "employed", "by", "the", "company"],
    "explanation": "【受動態】be動詞＋過去分詞（are employed）で「〜される（雇用されている）」という意味を表します。行為の主体は by ~ で示されることに注目しましょう。"
  },
  {
    "id": "U03_006",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "受動態（不規則動詞）",
    "difficulty": 1,
    "type": "choice",
    "questionEn": "A lot of money was [   ] in the robbery.",
    "questionJa": "その強盗事件で大金が盗まれた。",
    "choices": ["stolen", "stole", "steal", "stealing"],
    "correctAnswer": "stolen",
    "explanation": "【受動態】主語の A lot of money（大金）は「盗まれる」側なので、受動態（be動詞＋過去分詞）になります。steal（原形） - stole（過去形） - stolen（過去分詞）の不規則変化も確認しておきましょう。"
  },
  {
    "id": "U03_007",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "助動詞（否定の推量）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "It [   ] be true.",
    "questionJa": "それが本当であるはずがない。",
    "choices": ["can't", "mustn't", "shouldn't", "won't"],
    "correctAnswer": "can't",
    "explanation": "【助動詞】「〜のはずがない」という強い否定の推量は cannot (can't) を使います。must (〜に違いない) の反対の意味にあたります。mustn't は「〜してはいけない（禁止）」なので注意が必要です。"
  },
  {
    "id": "U03_008",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "助動詞＋完了形（推量）",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "彼らは外出したに違いない。",
    "words": ["They", "gone", "have", "must", "out"],
    "correctOrder": ["They", "must", "have", "gone", "out"],
    "explanation": "【助動詞＋完了形】must have + 過去分詞 で「（過去に）〜したに違いない」という過去の事象に対する強い推量を表します。長文の中で過去の出来事を振り返って考察する際に頻出します。"
  },
  {
    "id": "U03_009",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "助動詞（過去の習慣）",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "私は子供の頃、毎冬よくスキーに行ったものだ。",
    "words": ["When", "I", "I", "a", "child,", "every", "go", "skiing", "was", "winter", "would"],
    "correctOrder": ["When", "I", "was", "a", "child,", "I", "would", "go", "skiing", "every", "winter"],
    "explanation": "【助動詞】would (often) do で「（過去に）よく〜したものだ」という過去の習慣を表します。When I was a child のような過去の時を表す句や節とともに使われ、昔の回想を示すサインとなります。"
  },
  {
    "id": "U03_010",
    "unit": "3. 否定・受動態・助動詞",
    "theme": "助動詞＋完了形（後悔・非難）",
    "difficulty": 3,
    "type": "choice",
    "questionEn": "You [   ] eaten so much.",
    "questionJa": "あなたはそんなにたくさん食べるべきではなかったのに。",
    "choices": ["shouldn't have", "must not have", "cannot have", "needn't have"],
    "correctAnswer": "shouldn't have",
    "explanation": "【助動詞＋完了形】shouldn't have + 過去分詞 で「（過去に）〜するべきではなかったのに（してしまった）」という後悔や非難を表します。筆者の主張や評価を読み取る上で非常に重要な表現です。"
  },
  {
    "id": "U04_001",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "不定詞の名詞的用法",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "外出するときはドアに鍵をかけるのを忘れないでください。",
    "words": ["Don't", "door", "forget", "go", "lock", "out", "the", "to", "when", "you"],
    "correctOrder": ["Don't", "forget", "to", "lock", "the", "door", "when", "you", "go", "out"],
    "explanation": "【名詞的用法】forget to do で「〜することを忘れる」という意味になります。to lock the door 全体が forget の目的語（名詞のカタマリ）として働いています。"
  },
  {
    "id": "U04_002",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "不定詞（形式主語）",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "運転免許を持っていることは役に立つ。",
    "words": ["It", "a", "driver's", "have", "is", "license", "to", "useful"],
    "correctOrder": ["It", "is", "useful", "to", "have", "a", "driver's", "license"],
    "explanation": "【名詞的用法】It is ~ to do の構文です。It は形式的な主語であり、本当の主語は to have a driver's license（運転免許を持っていること）になります。"
  },
  {
    "id": "U04_003",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "不定詞の形容詞的用法",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "They have sent the applicant a form to [   ] in.",
    "questionJa": "彼らは応募者に記入するための用紙を送った。",
    "choices": ["fill", "filling", "filled", "be filled"],
    "correctAnswer": "fill",
    "explanation": "【形容詞的用法】名詞 a form を後ろから修飾する to fill in（記入するための）という形容詞のカタマリを作ります。前置詞 in を忘れやすいので注意しましょう。"
  },
  {
    "id": "U04_004",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "不定詞の副詞的用法",
    "difficulty": 1,
    "type": "sort",
    "questionJa": "私は英語を学ぶためにオーストラリアへ行く予定だ。",
    "words": ["Australia", "English", "I", "am", "going", "learn", "to", "to"],
    "correctOrder": ["I", "am", "going", "to", "Australia", "to", "learn", "English"],
    "explanation": "【副詞的用法】to learn English（英語を学ぶために）が目的を表す副詞のカタマリとして働いています。文の骨格（I am going to Australia）が完成した後に情報が追加される構造を意識しましょう。"
  },
  {
    "id": "U04_005",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "原形不定詞（知覚動詞）",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "I didn't see her [   ] in.",
    "questionJa": "私は彼女が入ってくるのを見なかった。",
    "choices": ["come", "to come", "came", "comes"],
    "correctAnswer": "come",
    "explanation": "【原形不定詞】see O do（Oが〜するのを見る）という知覚動詞の構文では、to のない原形不定詞を使います。Oとdoの間に「彼女が入る」という主語・述語の関係が成り立ちます。"
  },
  {
    "id": "U04_006",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "原形不定詞（使役動詞）",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "私たちは子供たちに夜更かしをさせない。",
    "words": ["We", "children", "don't", "late", "let", "stay", "the", "up"],
    "correctOrder": ["We", "don't", "let", "the", "children", "stay", "up", "late"],
    "explanation": "【原形不定詞】let O do（Oに〜させる）という使役動詞の構文です。the children が stay up late するのを let（許可する）という論理構造を掴みましょう。"
  },
  {
    "id": "U04_007",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "現在分詞による後置修飾",
    "difficulty": 2,
    "type": "sort",
    "questionJa": "あなたの友達と踊っている女の子は誰ですか？",
    "words": ["Who", "dancing", "friend", "girl", "is", "the", "with", "your"],
    "correctOrder": ["Who", "is", "the", "girl", "dancing", "with", "your", "friend"],
    "explanation": "【現在分詞】dancing with your friend という分詞のカタマリが、前の名詞 the girl を修飾しています。名詞の直後に ～ing が来た場合、修飾語の始まりを疑うのが読解のコツです。"
  },
  {
    "id": "U04_008",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "過去分詞による後置修飾",
    "difficulty": 2,
    "type": "choice",
    "questionEn": "Do you know the number of people [   ] by the government?",
    "questionJa": "政府に雇用されている人々の数を知っていますか？",
    "choices": ["employed", "employing", "employ", "to employ"],
    "correctAnswer": "employed",
    "explanation": "【過去分詞】people employed by the government（政府に雇用されている人々）という受動の意味を持った過去分詞のカタマリです。名詞の後に過去分詞が置かれるパターンも長文頻出です。"
  },
  {
    "id": "U04_009",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "分詞構文",
    "difficulty": 3,
    "type": "sort",
    "questionJa": "簡単な英語で書かれているので、この本は読みやすい。",
    "words": ["English,", "Written", "book", "easy", "in", "is", "read", "simple", "this", "to"],
    "correctOrder": ["Written", "in", "simple", "English,", "this", "book", "is", "easy", "to", "read"],
    "explanation": "【分詞構文】Written ~（書かれているので）という過去分詞から始まる副詞のカタマリが、主節の理由や条件などの状況を説明しています。主語（this book）との受動関係に注意しましょう。"
  },
  {
    "id": "U04_010",
    "unit": "4. 不定詞・分詞・動名詞",
    "theme": "動名詞",
    "difficulty": 1,
    "type": "choice",
    "questionEn": "The doctor suggested [   ] a long holiday.",
    "questionJa": "医者は長期休暇を取ることを提案した。",
    "choices": ["taking", "to take", "take", "taken"],
    "correctAnswer": "taking",
    "explanation": "【動名詞】suggest（提案する）の目的語には、不定詞（to do）ではなく動名詞（~ing）を用います。「休暇を取ること」という名詞のカタマリを作っています。"
  }
];
